apiVersion: 1

contactPoints:
  - orgId: 1
    name: Email Notifications
    receivers:
      - uid: email-receiver-001
        type: email
        settings:
          addresses:  {{ .Values.email.addresses }}
          singleEmail: true
        disableResolveMessage: false
